window.CLUBES_FAMOSOS = {
    "Brasil": [
        "Seleção Brasileira",
        "Flamengo",
        "Corinthians",
        "Palmeiras",
        "São Paulo",
        "Santos",
        "Vasco da Gama",
        "Fluminense",
        "Botafogo",
        "Grêmio",
        "Internacional",
        "Cruzeiro",
        "Atlético Mineiro",
        "Athletico Paranaense",
        "Bahia",
        "Fortaleza",
        "Sport",
        "Ceará",
        "Vitória",
        "Coritiba",
        "Goiás",
        "Red Bull Bragantino"
    ],

    "Europa": [
        "Real Madrid",
        "Barcelona",
        "Atlético de Madrid",
        "Sevilla",
        "Valencia",
        "Villarreal",
        "Athletic Club",
        "Manchester United",
        "Manchester City",
        "Liverpool",
        "Arsenal",
        "Chelsea",
        "Tottenham Hotspur",
        "Newcastle United",
        "Aston Villa",
        "Bayern München",
        "Borussia Dortmund",
        "Bayer Leverkusen",
        "RB Leipzig",
        "Eintracht Frankfurt",
        "Paris Saint-Germain",
        "Olympique de Marseille",
        "Olympique Lyonnais",
        "AS Monaco",
        "Juventus",
        "Inter de Milão",
        "Milan",
        "Napoli",
        "Roma",
        "Lazio",
        "Atalanta",
        "Benfica",
        "Porto",
        "Sporting CP",
        "Ajax",
        "PSV Eindhoven",
        "Feyenoord",
        "Celtic",
        "Rangers",
        "Galatasaray",
        "Fenerbahçe",
        "Besiktas"
    ],

    "América do Sul": [
        "Boca Juniors",
        "River Plate",
        "Independiente",
        "Racing Club",
        "San Lorenzo",
        "Peñarol",
        "Nacional",
        "Olimpia",
        "Cerro Porteño",
        "Colo-Colo",
        "Universidad de Chile",
        "Universidad Católica",
        "LDU Quito",
        "Barcelona SC",
        "Atlético Nacional",
        "Millonarios",
        "América de Cali"
    ],

    "América do Norte e México": [
        "Inter Miami",
        "LA Galaxy",
        "Los Angeles FC",
        "New York City FC",
        "Atlanta United",
        "Seattle Sounders",
        "Toronto FC",
        "Club América",
        "Chivas Guadalajara",
        "Cruz Azul",
        "Pumas UNAM",
        "Tigres UANL",
        "Monterrey"
    ],

    "África": [
        "Al Ahly",
        "Zamalek",
        "Wydad Casablanca",
        "Raja Casablanca",
        "Espérance de Tunis",
        "Mamelodi Sundowns"
    ],

    "Ásia e Oriente Médio": [
        "Al Hilal",
        "Al Nassr",
        "Al Ittihad",
        "Al Ahli",
        "Urawa Red Diamonds",
        "Vissel Kobe",
        "Kashima Antlers",
        "Yokohama F. Marinos",
        "Shanghai Port"
    ]
};